### PR TITLE
add Win32 DX11 C example

### PR DESCRIPTION
**Pull request by shawnhatori**

### CODE REVIEW

**Comment by ocornut** [comment]
I am not sure what Ben's stance would be on this, but some opinions:

- I believe it would be good to have a minimum testbed to run the C code interactively. We may ultimately need at least 2 testbeds to cover all OS, but Win32+DX11 and SDL or GLFW+OpenGL may be good.
- I would then be very highly in favor of putting a hard limit at not allowing more than those exact twos. Backporting all examples would be a non-optimal use of resources and is not the focus of dear bindings. Therefore making it clear those are ready-to-use testbeds but if people somehow want to use C with other combinations of backends, they can work from the [C++ examples](https://github.com/ocornut/imgui/tree/master/examples).
- I would be in favor of trying to make your code very closely mirror the C++ equivalent https://github.com/ocornut/imgui/blob/master/examples/example_win32_directx11/main.cpp (code ordering, names, comments) so the parallel is more evident and it would be near-automatic for me to update them if desired.

**Comment by ShironekoBen** [comment]
@shawnhatori 
Thanks for the PR!
Getting some functional example code in there definitely would improve usability for new users significantly, I think.

I've got a very hacky C test app here that I use to check things aren't utterly broken but it's a mess of stuff from all over the place and utterly unsuitable as an example - this code is far better!

@ocornut 
Yeah, that all sounds very sensible to me. 

If we can align this with the C++ versions then indeed that would be ideal as that makes them both easier to maintain and more comprehensible to users who may be familiar with the C++ code already. And given that the C++ examples are not particular C++-ish (in terms of making extensive use of non-C language features) it doesn't feel like they would need to diverge very much.

Personally speaking I'm happy to go either way on this - if a bit of tidying would get this code into a place where it's closer to the C++ version then that's great, if not then I could look at porting the C++ example over.

**Comment by shawnhatori** [comment]
Sorry for the late reply here. I'm biased obviously, but I have always preferred the clarity of "flat" code examples. They read easily top-to-bottom and focus exactly on the minimal number of necessary function calls, so for the purpose of an example, they clearly show you what needs to happen step-by-step. No forward declarations, no error checking, no cleanup. I find that examples with helper functions (or much worse, OOP structures) jump around the file and force the writer's abstraction on the reader (see [vulkan-tutorial.com](https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Base_code) for a particularly egregious example). 

Thankfully, ImGui's C++ examples are, as you said, very C-like, quite clear on their own, and perfectly suitable. And I completely understand wanting to keep the two examples in parity for maintenance. If so, feel free to close this PR. This code sample was just a stripped down version of my local dear_bindings tests.

**Comment by ocornut** [comment]
Any reason for closing this?

**Comment by ShironekoBen** [comment]
FWIW I've got one of the ImGui C++ samples "ported" into C and working, and am currently looking at which others to do, so I'm currently leaning towards just using those as they line up with the main ImGui codebase, but I'm more than happy to consider pulling this in as well if there's a feeling that having this in as a sample too would be beneficial.

**Comment by shawnhatori** [comment]
Sorry, I should have included a comment. Based on the above discussion, I closed it in favor of the goal to line the examples up with the C++ ones for easier maintainability across repos. I think that's perfectly reasonable. For that, a better starting point is probably just taking the existing file and tweaking it to compile in C.

**Pull request closed without merging**
